# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-illegal-windows-names
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: forbid-submodules
    -   id: name-tests-test
    -   id: no-commit-to-branch
    -   id: pretty-format-json
    -   id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.0
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [--config, ruff.toml, --fix ]
    # Run the formatter.
    - id: ruff-format
      args: [--config, ruff.toml]

- repo: https://github.com/development-incolume/incolume.py.githooks
  # https://github.com/development-incolume/incolume.py.githooks/blob/dev/README.md
  rev: 1.9.0
  hooks:
    - id: check-len-first-line
    #   args: [--nonexequi]
    - id: check-precommit-installed
    #   args: [--nonexequi]
    - id: check-valid-branchnames
    #   args: [--nonexequi]
    - id: check-valid-filenames
    #   args: ['--min-len=3', '--max-len=256', '--nonexequi']
    - id: detect-key
    #   args: [--nonexequi]
    - id: effort-message
    #   args: [--nonexequi]
    - id: footer-signed-off-by
    #   args: [--nonexequi]
    - id: insert-diff-commit
    #   args: [--nonexequi]
    - id: validate-message-commit
    #   args: [--nonexequi]