# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-illegal-windows-names
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: forbid-submodules
    -   id: name-tests-test
    -   id: no-commit-to-branch
    -   id: pretty-format-json
    -   id: trailing-whitespace
