# File .pre-commit-config.yaml

default_install_hook_types: [pre-commit, pre-push, prepare-commit-msg, post-commit]
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  # See https://pre-commit.com for more information
  # See https://pre-commit.com/hooks.html for more hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-illegal-windows-names
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: detect-private-key
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: forbid-submodules
    - id: name-tests-test
    - id: no-commit-to-branch
    - id: pretty-format-json
    - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.16.10
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [--config, ruff.toml, --fix ]
    # Run the formatter.
    - id: ruff-format
      args: [--config, ruff.toml]

- repo: https://github.com/development-incolume/incolume.py.githooks
  # https://github.com/development-incolume/incolume.py.githooks/blob/1.17.0/README.md
  rev: 1.18.2
  hooks:
    - id: check-len-first-line
    #   args: [--nonexequi|-N, --version|-V, --min-first-line=10, --max-first-line=256]
    - id: check-precommit-installed
    #   args: [--nonexequi|-N, --version|-V]
    - id: check-valid-branchname
    #   args: [--nonexequi|-N, --version|-V]
    - id: check-valid-filenames
    #   args: ['--min-len=3', '--max-len=256', '--nonexequi|-N', '--version|-V']
    - id: detect-key
    #   args: [--nonexequi|-N, --version|-V]
    - id: effort-message
    #   args: [--nonexequi|-N, --version|-V]
    - id: effort-random-message
    #   args: [--fixed|-F, --nonexequi|-N, --version|-V]
    - id: footer-signed-off-by
    #   args: [--nonexequi|-N, --version|-V]
    - id: insert-diff-commit
    #   args: [--nonexequi|-N, --version|-V]
    - id: validate-message-commit
    #   args: [--nonexequi|-N, --version|-V]
