site_name: Incolume Python Changelog
repo_url: https://github.com/development-incolume/incolume.py.changelog
repo_name: incolume.py.changelog
edit_uri: tree/dev/docs

theme:
  name: material
  language: pt-BR
  logo: asserts/img/cl_logo.png
  favicon: asserts/img/jedi_logo.png
  palette:
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: "#"

extra_css:
  - stylesheets/extra.css

watch:
  - incolume

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [incolume]
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: pt
          name: Português
          build: true
          default: true
        - locale: en
          name: English
          build: true
        - locale: fr
          name: Français
          build: false
        - locale: es
          name: Español
          build: false
        - locale: de
          name: Deutsch
          build: false

extra:
  commands:
    run: incolume

nav:
    - Home: index.md
    - API: api/index.md
    - 'User Guide':
        - Código de Conduta: user_guide/code_of_conduct.md
        - Medotologias:
            - Conventional Commit: user_guide/COVENTIONAL_COMMITS.md
            - Keep a CHANGELOG: user_guide/keep-a-changelog.md
            - MarkDown: user_guide/markdown.md
            - Mkdocs: user_guide/writing-your-docs.md
            - Semver: user_guide/semver.md
            - Zen Python: user_guide/zenpy.md
    - About:
        - Contributors: about/CONTRIBUTORS.md
        - License: about/LICENSE.md
        - 'Release Notes': about/CHANGELOG.md
