
[mypy]
python_version = 3.10
mypy_path = incolume/
namespace_packages = false
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

#[[tool.mypy.overrides]]
#disable_error_code = "attr-defined"
#disallow_untyped_defs = true
